"""
Django settings for VWBE project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os 
from dotenv import load_dotenv
# below import is for the neon external /serverless cloud base database
import dj_database_url
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bem=k9wq048u*_&banzp#nh)ttudt+r8l=u5715fuw^hsf4_9#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "*",
    "https://backend-production-1e63.up.railway.app",
    "https://valourwealth-frontend-psi.vercel.app",
    "https://tradegptlatest.vercel.app",
    "https://tradegptbackend-production.up.railway.app",
    "https://latestnewtradegptversion.vercel.app",
    
]


# This is for cloudflare video storage configurations:

load_dotenv()

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


AWS_ACCESS_KEY_ID = 'ea65d12791587a5f2e15788b7d34102a'
AWS_SECRET_ACCESS_KEY = '0ffd08d2ca6ba6a777377fb64f698d2e011006491f9577004223128c5a3ae4fa'
AWS_STORAGE_BUCKET_NAME = 'valourswealth'

AWS_S3_ENDPOINT_URL = 'https://67216f1510b2341aed5462099561b745.r2.cloudflarestorage.com'
AWS_S3_REGION_NAME = 'auto'  # R2 doesn't use real AWS regions

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False  # Set to True if you want signed URLs

DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024 * 1024  # 2GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024 * 1024  # 2GB

AWS_S3_MULTIPART_THRESHOLD = 50 * 1024 * 1024
AWS_S3_MULTIPART_CHUNKSIZE = 10 * 1024 * 1024





# Application definition

AUTH_USER_MODEL = 'main.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "whitenoise.runserver_nostatic",
    'main',
    'django_countries',
    "django.contrib.admindocs",
    'drf_yasg',
]
INSTALLED_APPS += ['storages']


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VWBE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VWBE.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}



MUX_TOKEN_ID = "96794e68-9334-404b-b2aa-94bda6f75506"
MUX_TOKEN_SECRET = "wGuZPStY+p3XZV3aA3+tR9zEXQsqXT+/njuMVeTxzHCRT9AsRwj9jobhgdGZvTUoQZgwpRdZvBL"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}



ALPHA_VANTAGE_API_KEY = "04RGF1U9PAJ49VYI"


CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1:8000",
    "https://192.168.1.12:3000",
    "https://backend-production-1e63.up.railway.app",
    "https://valourwealth-frontend-psi.vercel.app",
    "https://tradegptlatest.vercel.app",
    "https://tradegptbackend-production.up.railway.app",
    "https://latestnewtradegptversion.vercel.app",
]



# for smtp:

# app name in the google app: atmaxaportfolio
# password:  'eeuf fyps hicd iyzl'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mshoaibkaglur@gmail.com'
EMAIL_HOST_PASSWORD = 'rbug tyhd vtra xrtk'




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if os.getenv('RENDER') or os.getenv('RAILWAY_ENVIRONMENT'):
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


