# Generated by Django 5.1.1 on 2025-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_platformwalkthroughvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('6month', '6 Month Anniversary'), ('epic', 'Epic'), ('rare', 'Rare'), ('uncommon', 'Uncommon'), ('legendary', 'Legendary'), ('first', 'First Place'), ('second', 'Second Place'), ('third', 'Third Place'), ('founder', 'Founder')], max_length=20)),
                ('image', models.ImageField(upload_to='nfts/')),
                ('description', models.TextField(blank=True)),
                ('manually_assignable', models.BooleanField(default=False)),
            ],
        ),
    ]
