# Generated by Django 5.1.1 on 2025-04-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('platinum', 'Platinum')], default='free', max_length=20),
        ),
    ]
