# Generated by Django 5.1.1 on 2025-04-05 10:29

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofiles_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=VWBE.storage_backends.R2Storage(), upload_to='course_videos/'),
        ),
    ]
