# Generated by Django 5.1.1 on 2025-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='manual_public_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
