# Generated by Django 5.1.1 on 2025-07-17 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chatthread_ana_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftbadge',
            name='users',
            field=models.ManyToManyField(related_name='collected_nfts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='primary_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_badge_users', to='main.nftbadge'),
        ),
    ]
