# Generated by Django 5.1.1 on 2025-04-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_video_manual_public_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='manual_public_url',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
