# Generated by Django 5.1.1 on 2025-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_video_manual_public_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(blank=True, null=True),
        ),
    ]
