# Generated by Django 5.1.1 on 2025-07-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nftbadge_users_userprofiles_primary_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftbadge',
            name='users',
        ),
    ]
