# Generated by Django 5.1.1 on 2025-04-05 12:23

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='manual_public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=VWBE.storage_backends.R2Storage(), upload_to='course_videos/'),
        ),
    ]
