# Generated by Django 5.1.1 on 2025-04-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_video_manual_public_url_alter_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='manual_public_url',
        ),
        migrations.AddField(
            model_name='video',
            name='manual_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
