# Generated by Django 5.1.1 on 2025-07-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_win',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_duration',
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
