# Generated by Django 5.1.1 on 2025-07-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_trade_is_win_remove_trade_pnl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ana_message',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='ana_message',
            name='is_read',
        ),
    ]
