# Generated by Django 5.1.1 on 2025-04-15 05:19

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=VWBE.storage_backends.R2Storage(), upload_to='course_thumbnails/'),
        ),
    ]
