# Generated by Django 5.1.1 on 2025-04-21 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_video_thumbnail_video_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_date', models.DateField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_date', models.DateField()),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('position_size', models.PositiveIntegerField()),
                ('risk_reward_ratio', models.CharField(blank=True, max_length=20)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('entry_reason', models.TextField()),
                ('exit_reason', models.TextField()),
                ('emotional_state', models.TextField(blank=True)),
                ('market_conditions', models.TextField(blank=True)),
                ('what_went_well', models.TextField(blank=True)),
                ('what_went_wrong', models.TextField(blank=True)),
                ('lessons_learned', models.TextField()),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
