# Generated by Django 5.1.1 on 2025-04-21 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_webinar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='registered',
        ),
        migrations.AddField(
            model_name='webinar',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_webinars', to=settings.AUTH_USER_MODEL),
        ),
    ]
