# Generated by Django 5.1.1 on 2025-04-25 09:15

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=VWBE.storage_backends.R2Storage(), upload_to='profile_photos/'),
        ),
    ]
