# Generated by Django 5.1.1 on 2025-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userprofiles_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='recording_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
