# Generated by Django 5.1.1 on 2025-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
