# Generated by Django 5.1.1 on 2025-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_message_is_notification_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='starting_value',
        ),
        migrations.AddField(
            model_name='challenge',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='leaderboard_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='screenshots',
            field=models.FileField(blank=True, null=True, upload_to='challenge_screenshots/'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
