# Generated by Django 5.1.1 on 2025-05-05 03:55

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_challengeparticipant_current_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='prize',
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='screenshots',
            field=models.FileField(blank=True, null=True, storage=VWBE.storage_backends.R2Storage(), upload_to='challenge_screenshots/'),
        ),
    ]
