# Generated by Django 5.1.1 on 2025-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_challenge_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
