# Generated by Django 5.1.1 on 2025-05-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_challenge_participants_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed_quiz", models.BooleanField(default=False)),
                ("passed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.courselevel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course_level")},
            },
        ),
    ]
