# Generated by Django 5.1.1 on 2025-05-07 16:23

import VWBE.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_levelprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeginnerHubCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="Beginner Hub", max_length=100)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=VWBE.storage_backends.R2Storage(),
                        upload_to="beginnerhub_thumbnails/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeginnerHubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Fundamentals", "Fundamentals"),
                            ("Strategies", "Strategies"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="main.beginnerhubcourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeginnerHubVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=VWBE.storage_backends.R2Storage(),
                        upload_to="beginnerhub_videos/",
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="main.beginnerhubsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeginnerHubVideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.beginnerhubvideo",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "video")},
            },
        ),
    ]
