# Generated by Django 5.1.1 on 2025-05-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_beginnerhubcourse_beginnerhubsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beginnerhubcourse",
            name="manual_thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beginnerhubvideo",
            name="manual_video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beginnerhubvideo",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
