# Generated by Django 5.1.1 on 2025-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_beginnerhubcourse_manual_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beginnerhubvideo",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="beginnerhubvideo",
            name="order",
        ),
        migrations.AlterField(
            model_name="beginnerhubsection",
            name="level",
            field=models.CharField(
                choices=[
                    ("Fundamentals", "Fundamentals"),
                    ("Intermediate", " Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Strategies", "Strategies"),
                ],
                max_length=50,
            ),
        ),
    ]
