# Generated by Django 5.1.1 on 2025-05-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_remove_beginnerhubvideo_duration_seconds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beginnerhubvideoprogress",
            name="watched_seconds",
        ),
    ]
