# Generated by Django 5.1.1 on 2025-05-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_remove_beginnerhubvideoprogress_watched_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengeparticipant",
            name="status",
        ),
    ]
