# Generated by Django 5.1.1 on 2025-05-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_remove_challengeparticipant_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("inquiry_type", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="levelprogress",
            name="quiz_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
