# Generated by Django 5.1.1 on 2025-05-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_salesinquiry_levelprogress_quiz_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiles",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("analyst", "Analyst"), ("user", "User")],
                default="user",
                max_length=20,
            ),
        ),
    ]
