# Generated by Django 5.1.1 on 2025-05-13 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_userprofiles_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField()),
                ("published_date", models.DateField()),
                ("duration", models.CharField(max_length=10)),
                ("analyst_name", models.CharField(max_length=100)),
                ("analyst_title", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("key_points", models.JSONField()),
                ("is_platinum_only", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timeframe", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=10
                    ),
                ),
                (
                    "briefing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_ideas",
                        to="main.weeklybriefing",
                    ),
                ),
            ],
        ),
    ]
