# Generated by Django 5.1.1 on 2025-05-13 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_weeklybriefing_tradeidea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklybriefing",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
