# Generated by Django 5.1.1 on 2025-05-15 08:18

import VWBE.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_alter_weeklybriefing_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beginnerhubvideo",
            name="section",
        ),
        migrations.AlterUniqueTogether(
            name="beginnerhubvideoprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="beginnerhubvideoprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="beginnerhubvideoprogress",
            name="video",
        ),
        migrations.RemoveField(
            model_name="beginnerhubcourse",
            name="manual_thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="beginnerhubcourse",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="beginnerhubvideo",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="beginnerhubvideo",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="main.beginnerhubcourse",
            ),
        ),
        migrations.AddField(
            model_name="beginnerhubvideo",
            name="manual_thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beginnerhubvideo",
            name="thumbnail_file",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=VWBE.storage_backends.R2Storage(),
                upload_to="beginnerhub_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="beginnerhubcourse",
            name="category",
            field=models.CharField(
                choices=[("Stock", "Stock"), ("Forex", "Forex"), ("Crypto", "Crypto")],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="BeginnerHubSection",
        ),
        migrations.DeleteModel(
            name="BeginnerHubVideoProgress",
        ),
    ]
