# Generated by Django 5.1.1 on 2025-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_remove_beginnerhubvideo_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="webinar-thumbnails/"
            ),
        ),
    ]
