# Generated by Django 5.1.1 on 2025-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_alter_webinar_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="MT5Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("account_login", models.CharField(max_length=50)),
                ("balance", models.FloatField()),
                ("equity", models.FloatField()),
                ("margin", models.FloatField()),
                ("leverage", models.IntegerField()),
                ("open_positions", models.JSONField()),
                ("recent_trades", models.JSONField()),
            ],
        ),
    ]
