# Generated by Django 5.1.1 on 2025-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_mt5snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="mt5snapshot",
            name="portfolio_value",
            field=models.FloatField(default=0),
        ),
    ]
