# Generated by Django 5.1.1 on 2025-05-22 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_mt5snapshot_portfolio_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="mt5snapshot",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mt5_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
