# Generated by Django 5.1.1 on 2025-05-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_mt5snapshot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mt5snapshot",
            name="free_margin",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mt5snapshot",
            name="market_watch",
            field=models.JSONField(default=list),
        ),
    ]
