# Generated by Django 5.1.1 on 2025-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_analystchat_analystmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="mt5snapshot",
            name="assets",
            field=models.JSONField(default=list),
        ),
    ]
