# Generated by Django 5.1.1 on 2025-05-30 08:00

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_mt5snapshot_assets"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorsChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Markets", "Markets"),
                            ("Crypto", "Crypto"),
                            ("Forex", "Forex"),
                            ("Stocks", "Stocks"),
                        ],
                        default="Markets",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.FileField(
                        storage=VWBE.storage_backends.R2Storage(),
                        upload_to="editor_choices/",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
