# Generated by Django 5.1.1 on 2025-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_editorschoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklybriefing",
            name="manual_video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
