# Generated by Django 5.1.1 on 2025-06-10 08:20

import VWBE.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_weeklybriefing_manual_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklybriefing",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=VWBE.storage_backends.R2Storage(),
                upload_to="weekly_thumbnails/",
            ),
        ),
    ]
